// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// If you generate typed supabase definitions, import them here.
// For now, use `any` so the client compiles without generated types.

// Use a direct import path to the supabase.d.ts file
import type { Database } from '../../types/supabase.d.ts';

// Use LIVE Supabase credentials directly to bypass local setup issues
const supabaseUrl = 'https://owqgmdbzndkhdxfnvtqw.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93cWdtZGJ6bmRraGR4Zm52dHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Mjc1MDAsImV4cCI6MjA2NjMwMzUwMH0.8QQRXbHiy8t0n1x9Bnvn2ELxOLqHn1m8JXsWBuAXA1k';

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Supabase URL and Anon Key are required.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
